// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"seckill/internal/conf"
	"seckill/internal/data"
	"seckill/internal/server"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	_, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	// greeterRepo := data.NewGreeterRepo(dataData, logger)
	// greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logger)
	// greeterService := service.NewGreeterService(greeterUsecase, logger)
	// httpServer := server.NewHTTPServer(confServer, greeterService, logger)
	grpcServer := server.NewGRPCServer(confServer, logger)
	app := newApp(logger, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
